apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pricelist-frontend
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: pricelist-210
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps/manifests/pricelist-frontend
    repoURL: https://github.com/napsetsre/gitops-examples
    targetRevision: pricelist-210
  syncPolicy:
    automated:
      prune: true
      selfHeal: true